USE [master]
GO

/****** Object:  Database [AutoServiceSystem]    Script Date: 11/3/2021 5:53:53 AM ******/
DROP DATABASE [AutoServiceSystem]
GO

/****** Object:  Database [AutoServiceSystem]    Script Date: 11/3/2021 5:53:53 AM ******/
CREATE DATABASE [AutoServiceSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutoServiceSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoServiceSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutoServiceSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AutoServiceSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutoServiceSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutoServiceSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutoServiceSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutoServiceSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AutoServiceSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutoServiceSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [AutoServiceSystem] SET  MULTI_USER 
GO

ALTER DATABASE [AutoServiceSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutoServiceSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutoServiceSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutoServiceSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutoServiceSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutoServiceSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AutoServiceSystem] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AutoServiceSystem] SET  READ_WRITE 
GO


